### PR TITLE
fix(consola): use options.stderr

### PR DESCRIPTION
**Pull request by tjeeay**

### CODE REVIEW

**Comment by hobroker** [comment]
This is a pretty big bug. How wasn't this noticed before?

**Comment by pi0** [comment]
I think it was simply a typo. @hobroker any points keeping it as is now?

**Comment by hobroker** [comment]
@pi0, I might be wrong, I don't understand how it's `stderr` is used in the code. Sorry 🙂

**Comment by pi0** [comment]
in both cases (typo or not inline comment) blames are towards me :D I'll ensure it before merge/close.

**Pull request merged**
